# Generated by Django 4.1.7 on 2023-03-03 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='company name', max_length=100)),
                ('established_date', models.DateField(auto_now=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='user name', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
